language: python
python:
  - 2.7
install:
  - python bootstrap.py
  - bin/buildout -q
script:
  - bin/test
  - bin/vvv setup.py
  - bin/vvv src/spinnerchief

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com
